### ISSUE TITLE
Had to Manually Install Some Packages

### ISSUE THREAD

**Issue by ezequielsobrino** [InsuranceToolkits/promptflow#3]
Just wanted to drop a quick note - I had to manually install these packages to get the project running:
`pip install customtkinter Pillow openai`

Might be worth checking out if these are missing from the requirements or setup script, could save future users some time.

**Comment by radarhere** [comment]
All of those modules are listed in requirements.txt

https://github.com/InsuranceToolkits/promptflow/blob/acbb9bfd41d5265bd6c1ab6ac9f8530561717891/requirements.txt#L16
https://github.com/InsuranceToolkits/promptflow/blob/acbb9bfd41d5265bd6c1ab6ac9f8530561717891/requirements.txt#L71
https://github.com/InsuranceToolkits/promptflow/blob/acbb9bfd41d5265bd6c1ab6ac9f8530561717891/requirements.txt#L64
